export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const CHANTIER_TO_CHANGE='CHANTIER_TO_CHANGE';
export const PUBLIC_CHANGE='PUBLIC_CHANGE';
export const CONFIDENTIEL_CHANGE='CONFIDENTIEL_CHANGE';
export const PROFIL_CHANGE='PROFIL_CHANGE';